/** biome-ignore-all lint/style/useNamingConvention: enum naming */
export const GameVersions = {
    CIRCLE_PLUS: {
        kamai: "maimaiでらっくす CiRCLE PLUS",
        DX: "maimai でらっくす CiRCLE PLUS",
        EX: "maimai DX CiRCLE PLUS",
        CN: "",
    },
    CIRCLE: {
        kamai: "maimaiでらっくす CiRCLE",
        DX: "maimai でらっくす CiRCLE",
        EX: "maimai DX CiRCLE",
        CN: "",
    },
    PRISM_PLUS: {
        kamai: "maimaiでらっくす PRiSM PLUS",
        DX: "maimai でらっくす PRiSM PLUS",
        EX: "maimai DX PRiSM PLUS",
        CN: "舞萌DX 2026",
    },
    PRISM: {
        kamai: "maimaiでらっくす PRiSM",
        DX: "maimai でらっくす PRiSM",
        EX: "maimai DX PRiSM",
        CN: "舞萌DX 2025",
    },
    BUDDIES_PLUS: {
        kamai: "maimaiでらっくす BUDDiES PLUS",
        DX: "maimai でらっくす BUDDiES PLUS",
        EX: "maimai DX BUDDiES PLUS",
        CN: "",
    },
    BUDDIES: {
        kamai: "maimaiでらっくす BUDDiES",
        DX: "maimai でらっくす BUDDiES",
        EX: "maimai DX BUDDiES",
        CN: "舞萌DX 2024",
    },
    FESTIVAL_PLUS: {
        kamai: "maimaiでらっくす FESTiVAL PLUS",
        DX: "maimai でらっくす FESTiVAL PLUS",
        EX: "maimai DX FESTiVAL PLUS",
        CN: "",
    },
    FESTIVAL: {
        kamai: "maimaiでらっくす FESTiVAL",
        DX: "maimai でらっくす FESTiVAL",
        EX: "maimai DX FESTiVAL",
        CN: "舞萌DX 2023",
    },
    UNIVERSE_PLUS: {
        kamai: "maimaiでらっくす UNiVERSE PLUS",
        DX: "maimai でらっくす UNiVERSE PLUS",
        EX: "maimai DX UNiVERSE PLUS",
        CN: "",
    },
    UNIVERSE: {
        kamai: "maimaiでらっくす UNiVERSE",
        DX: "maimai でらっくす UNiVERSE",
        EX: "maimai DX UNiVERSE",
        CN: "舞萌DX 2022",
    },
    SPLASH_PLUS: {
        kamai: "maimaiでらっくす Splash PLUS",
        DX: "maimai でらっくす Splash PLUS",
        EX: "maimai DX Splash PLUS",
        CN: "",
    },
    SPLASH: {
        kamai: "maimaiでらっくす Splash",
        DX: "maimai でらっくす Splash",
        EX: "maimai DX Splash",
        CN: "舞萌DX 2021",
    },
    DX_PLUS: {
        kamai: "maimaiでらっくす PLUS",
        DX: "maimai でらっくす PLUS",
        EX: "maimai DX PLUS",
        CN: "",
    },
    DX: {
        kamai: "maimaiでらっくす",
        DX: "maimai でらっくす",
        EX: "maimai DX",
        CN: "舞萌DX",
    },
    FINALE: {
        kamai: "maimai FiNALE",
        DX: "maimai FiNALE",
        EX: "maimai FiNALE",
        CN: "maimai FiNALE",
    },
    MILK_PLUS: {
        kamai: "maimai MiLK PLUS",
        DX: "maimai MiLK PLUS",
        EX: "maimai MiLK PLUS",
        CN: "maimai MiLK PLUS",
    },
    MILK: {
        kamai: "maimai MiLK",
        DX: "maimai MiLK",
        EX: "maimai MiLK",
        CN: "maimai MiLK",
    },
    MURASAKI_PLUS: {
        kamai: "maimai MURASAKi PLUS",
        DX: "maimai MURASAKi PLUS",
        EX: "maimai MURASAKi PLUS",
        CN: "maimai MURASAKi PLUS",
    },
    MURASAKI: {
        kamai: "maimai MURASAKi",
        DX: "maimai MURASAKi",
        EX: "maimai MURASAKi",
        CN: "maimai MURASAKi",
    },
    PINK_PLUS: {
        kamai: "maimai PiNK PLUS",
        DX: "maimai PiNK PLUS",
        EX: "maimai PiNK PLUS",
        CN: "maimai PiNK PLUS",
    },
    PINK: {
        kamai: "maimai PiNK",
        DX: "maimai PiNK",
        EX: "maimai PiNK",
        CN: "maimai PiNK",
    },
    ORANGE_PLUS: {
        kamai: "maimai ORANGE PLUS",
        DX: "maimai ORANGE PLUS",
        EX: "maimai ORANGE PLUS",
        CN: "maimai ORANGE PLUS",
    },
    ORANGE: {
        kamai: "maimai ORANGE",
        DX: "maimai ORANGE",
        EX: "maimai ORANGE",
        CN: "maimai ORANGE",
    },
    GREEN_PLUS: {
        kamai: "maimai GreeN PLUS",
        DX: "maimai GreeN PLUS",
        EX: "maimai GreeN PLUS",
        CN: "maimai GreeN PLUS",
    },
    GREEN: {
        kamai: "maimai GreeN",
        DX: "maimai GreeN",
        EX: "maimai GreeN",
        CN: "maimai GreeN",
    },
    MAIMAI_PLUS: {
        kamai: "maimai PLUS",
        DX: "maimai PLUS",
        EX: "maimai PLUS",
        CN: "maimai PLUS",
    },
    MAIMAI: {
        kamai: "maimai",
        DX: "maimai",
        EX: "maimai",
        CN: "maimai",
    },
} as const;
export type GameVersions = (typeof GameVersions)[keyof typeof GameVersions];
